### ISSUE TITLE
add preact FE

### ISSUE THREAD

**Issue by kapusta** [kapusta/pzgps#11]
Useful Docs
- [preact site](https://preactjs.com/)
- [switching to Preact](https://preactjs.com/guide/switching-to-preact)
- [preact-compat](https://github.com/developit/preact-compat)

Todo
- [x] [use preact boilerplate](https://github.com/developit/preact-boilerplate)
- [x] [use preact-router](https://github.com/developit/preact-router)
- [x] [investigate decko](https://github.com/developit/decko)
- [x] port index.js and App.js from the reactjs FE

**Comment by kapusta** [comment]
gunna call it shipped in v1.13.1

**Comment by developit** [comment]
Nice! Congrats 🎉
